### ISSUE TITLE
how about merge to official repo

### ISSUE THREAD

**Issue by Hokwang** [stevehipwell/helm-charts#1]
Hello.

Today I know your helm charts because of nexus helm chart issue from sonatype.

Here's my opinion.
1. How about merge your nexus charts to offical helm chart repo (https://github.com/helm/charts/tree/master/stable/sonatype-nexus) ?
2. there's no jira/confluence chart in official helm chart repo.
How about push your jira/confluence chart to that?

Thanks,

**Comment by stevehipwell** [comment]
@Hokwang thank you for getting in contact. Firstly my *Nexus 3* helm chart would be a breaking change to the one currently in the **stable** repo; if it was even merged (see next point). Secondly the official *Helm* chart repo is no longer taking new chart submissions and will be [deprecated](https://github.com/helm/charts#deprecation-timeline) in May. There is more information there about how the *Helm* chart ecosystem will function.
