### ISSUE TITLE
Continuous crashloopbackoff of the jira container

### ISSUE THREAD

**Issue by MrAmbiG** [stevehipwell/helm-charts#107]
format 1
==============
values.yml

```
persistence:
  enabled: true
  existingClaim: jirapvc
postgresql:
  enabled: true

```
error
-------------
```
$ helm -n jira upgrade -i jira stevehipwell/jira-software -f jira.yml
Release "jira" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

format 2
============
values.yml

```
persistence:
  enabled: true
  accessMode: ReadWriteMany
  storageClass: nfsdefault
  existingClaim: jirapvc
psql:
  host:
  port: 5432
  database: jiradb
  username: jiraadmin
  password:
    secret: jirapsql
    key: password
```
	
error
-------------
```
kubectl -n jira logs pod/jira-jira-software-7b6b5c8f7-gd2rx
INFO:root:Generating /etc/container_id from template container_id.j2
INFO:root:Generating /opt/atlassian/jira/conf/server.xml from template server.xml.j2
INFO:root:Generating /opt/atlassian/jira/atlassian-jira/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
INFO:root:/var/atlassian/application-data/jira/dbconfig.xml exists; skipping.
Traceback (most recent call last):
  File "/entrypoint.py", line 26, in <module>
    start_app(f'{JIRA_INSTALL_DIR}/bin/start-jira.sh -fg', JIRA_HOME, name='Jira')
  File "/entrypoint_helpers.py", line 85, in start_app
    set_perms(home_dir, env['run_user'], env['run_group'], 0o700)
  File "/entrypoint_helpers.py", line 34, in set_perms
    shutil.chown(path, user=user, group=group)
  File "/usr/lib/python3.8/shutil.py", line 1296, in chown
    os.chown(path, _user, _group)
PermissionError: [Errno 1] Operation not permitted: '/var/atlassian/application-data/jira'
```

**Comment by stevehipwell** [comment]
Hi @MrAmbiG it'd be useful to know a bit more information about your setup such as K8s version and provider as well as a bit of information about what you're trying to achieve?

For _Format 1_ you are specifying that you wish to use the bundled [PostgreSQL](https://artifacthub.io/packages/helm/bitnami/postgresql/4.2.2) chart. Based on the error I suspect that your version of K8s is does not have the APIs to support the bundled chart (PostgreSQL 10). If this is the case the approach in _Format 2_ would be correct (or you could raise an issue with Bitnami to get their charts to support different API versions).

For _Format 2_ you are specifying that you will be providing the PostgreSQL instance to run Jira on, so you will need to provide the host for that instance to the chart or it will not work.

As a final bit of information, the bundled PostgreSQL instance is provided for convenience but I'd recommend using a separate instance as using the bundled one ties you in to a shared lifecycle. Also Atlassian does not keep the PostgreSQL compatibility for Jira (and confluence) very up to date and as I don't use the bundled PostgreSQL I only upgrade this when both Jira & Confluence support the same version of PostgreSQL, which currently limits us to PostgreSQL v10.

**Comment by MrAmbiG** [comment]
@stevehipwell  appreciate your response.
the version of kubernetes is 1.17.4. I Redacted the host. I will try again with some more additional settings and update you soon.
