### ISSUE TITLE
Fluentd Aggregator deployment

### ISSUE THREAD

**Issue by AswalGaurang** [stevehipwell/helm-charts#1086]
When i set persistence to true i run into this error while installing.
Error: UPGRADE FAILED: cannot patch "fluentd-aggregator" with kind StatefulSet: StatefulSet.apps "fluentd-aggregator" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

**Comment by stevehipwell** [comment]
@AswalGaurang I need more context about the chart version and values you're using plus if this is an upgrade or a fresh install? Based on the error it looks like an upgrade? I'm not sure it's possible to upgrade to add persistence, but that shouldn't be a problem given the lack of state you should be able to uninstall and then re-install with the new values.
