### ISSUE TITLE
Nexus3 - Will existingClaim support be reintroduced?

### ISSUE THREAD

**Issue by sule26** [stevehipwell/helm-charts#1087]
I've been using EFS for Nexus data and previously configured it using the `existingClaim` option. However, in newer versions of the Helm chart, this option is no longer supported, making it impossible to upgrade without reconfiguring storage. Is there any chance that `existingClaim` will be reintroduced in future releases?

**Comment by stevehipwell** [comment]
@sule26 the existing claim support was only on the legacy `Deployment` implementation which has been removed as part of [`v5.x.x`](https://github.com/stevehipwell/helm-charts/blob/main/charts/nexus3/CHANGELOG.md#v500---2024-09-10). You are going to have to both switch to a StatefulSet and migrate away from _OrientDB_. FYI I would not have recommended mounting an EFS volume for the main persistence layer, I'd have recommended using `extraVolumes` & `extraVolumeMounts` for EFS with an EBS volume used for the main persistence.

**Comment by sule26** [comment]
@stevehipwell Thanks for answering! I was already planning to migrate to EBS, and now it seems like the only way.
