### ISSUE TITLE
nexus3 relies on jq which is not present in the image

### ISSUE THREAD

**Issue by grumpydude** [stevehipwell/helm-charts#120]
In configure.sh, as of the most recent commit to fix the repository secrets, there is now a requirement that the sonatype/nexus3 image will have 'jq' installed. However, it is not installed on the image that is maintained by sonatype. Refer the following code:

```
      repo_name="$(jq -r '.name' "${json_file}")"
      repo_password_file="${base_dir}/secret/repo-credentials/${repo_name}"
      if [ -f "${repo_password_file}" ]
      then
        repo_password="$(cat "${repo_password_file}")"
        sed -i "s/PASSWORD/${repo_password}/g" "${json_file}"
      fi
```

Yes, one can create a downstream image, but I suspect that's there might be other ways to deal with it using what's installed on the image.

**Comment by stevehipwell** [comment]
@grumpydude thanks for bringing this to my attention; it should be resolved by PR https://github.com/stevehipwell/helm-charts/pull/121.

**Comment by grumpydude** [comment]
Yes this works, but it's exposed an ordering issue that you have with roles and repos. If you try to create a role with a repo based privilege that doesn't exist yet, the API will respond with the following:

```
Privilege 'nx-repository-view-maven2-fancy-repo-browse' contained in role 'maven-fancy-role-publish' not found.
```
I can raise this as another issue.

**Comment by stevehipwell** [comment]
@grumpydude I'm closing this issue as resolved and we can look at configure order in https://github.com/stevehipwell/helm-charts/issues/122.
