### ISSUE TITLE
Jira/Confluence support 2021?

### ISSUE THREAD

**Issue by phenri00** [stevehipwell/helm-charts#149]
Effective from 2 February 2021, Atlassian will end new server licence sales and cease any new feature development for its server product line. Do you know if there still be updated(security patches) docker images from Atlassian? If yes, will you keep the helm charts up to date?

Thank you for all the work on the charts. Really appreciate them!

**Comment by stevehipwell** [comment]
@phenri00 I will continue to update these charts for as long as they're able to be used. I'm not aware of Atlassian's plans around keeping the Docker image up to date but I'd like to think that they will patch for security even if there is no more proddev going on.

**Comment by sylus** [comment]
As I understood server licenses are no longer happening but data center would still be going?

I think i am understanding that correctly?

**Comment by stevehipwell** [comment]
@sylus that's the way I understand it. I don't have a data center license so I'm not sure how that works from the aspect of a Helm chart?

**Comment by sylus** [comment]
Oh it just worked for me with no changes just entered the license when the server was up. 

Thanks for all the work you have done :D

**Comment by stevehipwell** [comment]
@sylus does the data center license allow you to run a HA setup or is it still just a single server?

**Comment by sylus** [comment]
I have only run the single server atm, but good question I will look into that :)
