### ISSUE TITLE
No ability to specify Liveness/Readiness probes timeout

### ISSUE THREAD

**Issue by Yrok472** [stevehipwell/helm-charts#151]
Hello :)

I'm using this jira-software chart on my local server. It's not very fast + i'm using internal database. So, sometimes pod restarts before complete initialization. I know that i can path deployment params using kubectl apply after chart deploy, but maybe you can add this options for chart. Thank you!

**Comment by stevehipwell** [comment]
@Yrok472 I'm not sure I understand your query? If you're running the chart and it's slow then that is down to how you're running it and the choices you made when setting the values. For example running the chart in Kind using the built in H2 database would work but would be slow and unsuitable for anything other than testing. You need to look into the Docker image resource requirements for Jira (it's JVM) and PostgreSQL if you're running the sub-chart; for comparison we use 2 CPUs and 4 Gb RAM combined with an external cloud hosted DB and we will need to increase this soon.

**Comment by Yrok472** [comment]
Sometimes it take more than 10 minutes to start jira and default probes timeout restart my jira many times. I want to change default count of probes tries for my installation.

**Comment by stevehipwell** [comment]
@Yrok472 I understand. I've just released `v4.0.2` with dynamic probe configuration.

**Comment by Yrok472** [comment]
Thank you! I'll try to verify.

**Comment by Yrok472** [comment]
It works :)
