### ISSUE TITLE
controlPlane.spec query

### ISSUE THREAD

**Issue by Callum1201** [stevehipwell/helm-charts#157]
Hey,

I'm trying to get my head around the istio-operator. I've set up the istio profile to use default but also need to specify kiali as an additional spec.

I'm assuming this comes under controlPlane.spec and the additionalComponents value but I can't seem to find the format for specifying this

**Comment by stevehipwell** [comment]
@Callum1201 since the v1.8 release of Istio add-ons are no longer supported. I'd suggest using the respective operators (same for Jaeger); but there is an extras folder in the Istio repo with yaml to deploy add-ons for testing but you would need to do it manually.

**Comment by Callum1201** [comment]
Thanks for that :)

**Comment by stevehipwell** [comment]
@Callum1201 you could always install the last chart version for v1.7 to install the add-ons before upgrading the chart to get v1.8. I know Prometheus works that way and I assume Kiali would too.
