### ISSUE TITLE
confluence-server/database

### ISSUE THREAD

**Issue by vin-bdx** [stevehipwell/helm-charts#177]
Hi @stevehipwell !

A question about your confluence-server helm chart, for the moment we can only connect to PSQL. Can you tell me if connection update to SQL Server Database is scheduled? 

Best regards

**Comment by stevehipwell** [comment]
Hi @vin-bdx. I don't have any plans to support alternative databases, but I'd be willing to accept a PR.

**Comment by vin-bdx** [comment]
Ok, thanks for the quick feedback.
