### ISSUE TITLE
sonarqube - wrong rendering of postgresql port in SONAR_JDBC_URL 

### ISSUE THREAD

**Issue by NiasSt90** [stevehipwell/helm-charts#178]
the printf `"jdbc:postgresql://%s:%d/%s"` with %d was rendered as float64 instead of int.
then the url looks like:
`jdbc:postgresql://ot-sonar-postgresql:%!d(float64=5433)/sonardb`

therefore sonarqube dont start with postgresql.

**Comment by stevehipwell** [comment]
@NiasSt90 I thought I'd already fixed this but looking at the code it's not right. I use the default port with this chart which is why it works for me. I'm happy to take a PR to fix this.
