### ISSUE TITLE
Nexus3 helm chart - No support for adding pod labels

### ISSUE THREAD

**Issue by eric-engberg** [stevehipwell/helm-charts#193]
The current helm chart does not support adding additional labels to the pods. In azure assigning an MSI to a pod is done via aad-pod-identiy and the label aadpodidbinding.

**Comment by stevehipwell** [comment]
@eric-engberg I'll look at adding pod label options to my charts for this use case.

It's a shame that Microsoft didn't use one of the standard patterns such as a pod annotation or an object with a pod selector. By using pod labels, idiomatic charts need to be modified to support this pattern.

**Comment by stevehipwell** [comment]
MR https://github.com/stevehipwell/helm-charts/pull/194 resolves this.

**Comment by eric-engberg** [comment]
Wow that was fast.  Thanks.
