### ISSUE TITLE
Confluence - Add parameter in CATALINA_OPTS

### ISSUE THREAD

**Issue by phenri00** [stevehipwell/helm-charts#23]
Need to add following parameter in CATALINA_OPTS: 

"-Dofficeconnector.spreadsheet.xlsxmaxsize=134217728" 

Do I modify the deployment file for JVM_SUPPORT_RECOMMENDED_ARGS? Or is there a better way to do this?

Im having following issue:

https://confluence.atlassian.com/confkb/viewing-excel-error-with-the-message-error-rendering-macro-viewxls-com-benryan-conversion-conversionexception-com-benryan-conversion-conversionexception-cannot-convert-spreadsheet-744327791.html?_ga=2.14265335.1545115065.1591025617-76658230.1587116556

Thanks!

**Comment by stevehipwell** [comment]
@phenri00 I've added the ability to specify `envVars.opts` in #25 which should allow you to add your custom setting.

**Comment by phenri00** [comment]
Good stuff! Thank you for the work.
