### ISSUE TITLE
 [jira-software] chart templating issue

### ISSUE THREAD

**Issue by dcardellino** [stevehipwell/helm-charts#245]
Hello,

Like in #136 in jira-software i also receive a templating error.
`Error: template: jira-software/templates/deployment.yaml:79:43: executing "jira-software/templates/deployment.yaml" at <include "jira-software.postgresql.fullname" .>: error calling include: template: jira-software/templates/_helpers.tpl:77:12: executing "jira-software.postgresql.fullname" at <{{template "postgresql.fullname" $postgresContext}}>: template "postgresql.fullname" not defined`

I have a temporary workaround, cloning the repo locally an edit _helpers.tpl on line 77 to `{{ template "postgresql.primary.fullname" $postgresContext }}`

**Comment by stevehipwell** [comment]
@dcardellino I've managed to introduce this issue into a number of my charts so I'll fix them in a single PR as well as add some ingress maintenance.
