### ISSUE TITLE
After Ingress Maintenance, Ingress can't be created

### ISSUE THREAD

**Issue by dcardellino** [stevehipwell/helm-charts#252]
If I deploy jira-software, an ingress can't be deployed, because there is a templating issue in `
helm-charts/charts/jira-software/templates/ingress.yaml` on line 20.

```
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
 ```

There is a missing key `spec`. The part of the code should look like this:
```
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
```

**Comment by stevehipwell** [comment]
Thanks for reporting this, I'll patch ASAP.
