### ISSUE TITLE
[sonarqube] Add extra containers support

### ISSUE THREAD

**Issue by akath19** [stevehipwell/helm-charts#298]
We're looking to use your Sonarqube helm chart (it's the most featured & trusted one), however, we required adding an extra container to the Sonarqube deployment (a proxy to connect to external DBs).

@stevehipwell I've opened #297 with the required changes to support this, can you review and let me know if it's OK?

**Comment by stevehipwell** [comment]
Thank you @akath19, I've reviewed your PR and left some comments but am happy to merge the changes as soon as these are addressed. I'll be releasing a new chart version to support SonarQube v9.0 soon but I'd like to get your changes in first to support the v8.9 LTS release on the current chart major version.

**Comment by akath19** [comment]
Done, thanks for the quick response and comments!
