### ISSUE TITLE
Environment variables name are no correct

### ISSUE THREAD

**Issue by oisis** [stevehipwell/helm-charts#323]
In current SonarQube chart version PostgreSQL configuration is not working because of wrong ENV VAR names.

Please change environment variables names int this file:
https://github.com/stevehipwell/helm-charts/blob/master/charts/sonarqube/templates/deployment.yaml#L113-L144
Currently SonarQube run/config script is not reading those values.
So please change:
```
SONAR_JDBC_URL
SONAR_JDBC_USERNAME
SONAR_JDBC_PASSWORD
```
to:
```
SONARQUBE_JDBC_URL
SONARQUBE_JDBC_USERNAME
SONARQUBE_JDBC_PASSWORD
```
I'm not sure what about rest of them for now.

**Comment by stevehipwell** [comment]
@oisis where are you sourcing this information from? The [official docs](https://docs.sonarqube.org/latest/setup/environment-variables/) show the current variables as correct and the [installation guide](https://docs.sonarqube.org/latest/setup/install-server/) shows the variables that you've quoted as deprecated.

**Comment by oisis** [comment]
I was trying to setup SonarQube with Postgres on K8s with your chart and i couldn't get it working. After some small investigation all was set up properly but had to change env variables names. Please check this:
https://github.com/SonarSource/docker-sonarqube/blob/master/7/community/Dockerfile#L7-L11
https://github.com/SonarSource/docker-sonarqube/blob/master/8/community/run.sh#L49-L51
I believe, you have to use the same ENV VAR name as is in SonarQube docker images.

**Comment by stevehipwell** [comment]
@oisis the latest chart is for v9 and doesn't support v7, if it works so be it but I doubt it would, or v8, which should work fine as there haven't been any chart changes that would stop this. If you want to use v7 or v8 in a supported way please use an older chart version.

To clarify the issue you reported (I'm assuming that you're on v8 or v9) the function you've highlighted `set_prop_from_deprecated_env_var` specifically calls out that the env variables you so confidently told me I should swap in are in fact deprecated, I gave you the link to the official documentation and a deprecation notice above.

These charts are provided as is and with the usual advice of not running DBs in K8s; I personally use RDS instances and can confirm that the env variables in the chart work correctly. I wouldn't go as far as to say that the embedded PSQL chart definitely work, although it did last time I tested it. I'm happy to look at the values you're providing to see if there is anything obvious but besides that you could use a different source for PSQL, such as a separate chart, and pass in the connection values.

**Comment by oisis** [comment]
Yes, you are right, i was trying to setup SQ 7 with latest chart version. Will try next to setup later SQ 8 and 9(upgrade process from 7) with this chart. Anyway thanks for your help. If chart is working ok with SQ9 i think you can close this ticket.

**Comment by stevehipwell** [comment]
@oisis I remembered wrong, I've never supported v7 in my chart but there is a v7 chart in the [legacy repo](https://github.com/helm/charts).

In general a Helm chart should be compatible with a different patch version to the one it's released with; it might be compatible with a different minor version; but it's unlikely to be compatible with a different major version. This rule is made even more likely with something complex, like SonarQube, or something not necessarily designed for Kubernetes or even containers, like SonarQube.
