### ISSUE TITLE
[sonarqube] github signing in 

### ISSUE THREAD

**Issue by dynamicat** [stevehipwell/helm-charts#327]
I have deployed sonarqube 4.0.0 with the helm chart.  Everything is setup and all works correctly except the GitHub Authentication.  I completed all the fields using the same clientid etc as used with setting up sonar with github actions.

When I try to login with the github account it redirects me back to the login page again.  Did you have any experience with this or is there something I missed?

sessions/new?return_to=%2F%3Ferror%3Dredirect_uri_mismatch%26error_description%3DThe%2Bredirect_uri%2BMUST%2Bmatch%2Bthe%2Bregistered%2Bcallback%2BURL%2Bfor%2Bthis%2Bapplication.%26error_uri%3Dhttps%253A%252F%252Fdocs.github.com%252Fapps%252Fmanaging-oauth-apps%252Ftroubleshooting-authorization-request-errors%252F%2523redirect-uri-mismatch%26state%3Db0jodbgpfpbvu9rencok4om9n1

**Comment by stevehipwell** [comment]
@dynamicat it looks like your OAuth configurations is incorrect based on the error URL returned. As far as the Helm chart goes, I have nothing to do with the SonarQube implementation and I haven't personally used GitHub integration.

**Comment by dynamicat** [comment]
Ye i fixed it. But thanks for the reply.

**Comment by naviat** [comment]
@dynamicat could you share your value sample for Github signing in? appreciate it!
