### ISSUE TITLE
Meet error when deploy confluence-server on openshift

### ISSUE THREAD

**Issue by Karl-br** [stevehipwell/helm-charts#35]
Hi Team

helm install my-release stable/confluence-server
when i use the command to deploy confluence on Openshift 4.4 i meet CrashLoopBackOff error.
here is the log

INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
INFO:root:/var/atlassian/application-data/confluence/confluence.cfg.xml exists; skipping.
INFO:root:User is currently root. Will downgrade run user to confluence
INFO:root:Running Confluence with command '/bin/su', arguments ['/bin/su', 'confluence', '-c', '/opt/atlassian/confluence/bin/start-confluence.sh -fg']
su: System error

Please tell me how to deal with this problem.
Thank you

**Comment by phenri00** [comment]
Default policy for Openshift is to block RunAsAny, meaning running as root is not allowed. Could that be the issue?

**Comment by Karl-br** [comment]
OK so the namespace=confluence-test.And also i have already run the command
oc adm policy add-scc-to-user privileged -n confluence-test -z default
But it not work.

**Comment by stevehipwell** [comment]
@Karl-br I've not run this chart on Openshift. I would suggest that you reach out to Atlassian to confirm that their docker image is Openshift compatible. If it is I'll take a look at the chart to make sure it's using the correct security settings.

**Comment by stevehipwell** [comment]
@Karl-br you probably want to take a look at the Shared directory and user IDs section on the [Confluence Docker image](https://hub.docker.com/r/atlassian/confluence-server/) docs. You can currently modify the pod security context through the `securityContext` variable but I'm looking at modernising these charts so they will also support a separate security context for the primary container.
