### ISSUE TITLE
istio-operator chart needs ClusterRole updates

### ISSUE THREAD

**Issue by jrsdav** [stevehipwell/helm-charts#359]
I recently discovered when using the [istio-operator](https://github.com/stevehipwell/helm-charts/tree/master/charts/istio-operator) chart, the Istio Operator is failing to reconcile changes to `IstioOperator` CR's, preventing removal of Istio components when uninstalling the chart. 

This is due to a missing RBAC permission in the operator's `ClusterRole`, which has been fixed in upcoming Istio releases but is not yet present in version `1.11.4` (which this chart is currently using).

Refer to the following issue: 
https://github.com/istio/istio/issues/35016#issuecomment-965669856

This can be fixed now by adding `pods/portforward` to the [`ClusterRole` template](https://github.com/stevehipwell/helm-charts/blob/6dfa46396b955b8b809b9a40683d3e4bb5de1bbc/charts/istio-operator/templates/clusterrole.yaml#L102), or will eventually be taken care of when you update to later releases of Istio.

I'll submit a PR.

**Comment by stevehipwell** [comment]
Thanks @jrsdav, let's get your PR merged to fix this.

**Comment by stevehipwell** [comment]
Resolved by #360.
