### ISSUE TITLE
Nexus3: Ability to add BasicAuth to Endpoints in ServiceMonitor

### ISSUE THREAD

**Issue by eric-engberg** [stevehipwell/helm-charts#392]
Nexus requires basic auth to scrape the metrics.  The ServiceMonitor resource does not currently support adding that field

**Comment by eric-engberg** [comment]
Ah I didn't even think of that.  Yeah that seems to work ok.  Might not be a bad idea to add the ability for BasicAuth though.  If I can find time I can try to put in a PR if you don't want to do it.

**Comment by stevehipwell** [comment]
@eric-engberg I'll add this in the next release.

**Comment by stevehipwell** [comment]
@eric-engberg I haven't forgotten about this, I've just been waiting on a Nexus release. If you're stuck without it I could do a release to add this without the Nexus release?

This will be released as `serviceMonitor.endpointConfig` to enable full `ServiceMonitor` endpoint customisation, I assume that this will work correctly for your use-case?

**Comment by eric-engberg** [comment]
I'm good with the work around you gave me.  For now at least.. I can wait for a nexus update

**Comment by eric-engberg** [comment]
Ok well it turns out there is an issue with enabling anonymous access to metrics. See https://github.com/stevehipwell/helm-charts/issues/412
