### ISSUE TITLE
nx-anonymous policy hard coded for anonymous user

### ISSUE THREAD

**Issue by eric-engberg** [stevehipwell/helm-charts#412]
When metrics and anonymous access are enabled the current helm chart is hard coded to add the policy "nx-anonymous" to the anonymous user.  This allows anonymous reads of the repository for all repos.  If enabling anonymous metrics the only policy that needs to be applied is "nx-metrics" but there is no way to currently do that.

**Comment by stevehipwell** [comment]
@eric-engberg the automation scripts were written for a specific use case and although I've tried to make them work for anyone there are some things like this which have been missed. Let me take a look at this and I'll put out a minor version which will hopefully solve your problem.

**Comment by stevehipwell** [comment]
@eric-engberg looking through the docs enabling anonymous access does by default enable access to all repos, I've generally tried to keep this as simple as possible although looking through the code again it's anything but simple.

If you want to take a look at #413 this should fix your issues? I don't have time to fully test this as I no longer directly consume the chart so I'll just be testing the templated output against the previous version.
