### ISSUE TITLE
PlantUML behind reversed proxy not working

### ISSUE THREAD

**Issue by eranhirs** [stevehipwell/helm-charts#415]
As mentioned in multiple PlantUML issues ([#64](https://github.com/plantuml/plantuml-server/issues/64), [#163](https://github.com/plantuml/plantuml-server/issues/163)), there is an issue when deploying PlantUML behind a reversed proxy, where it redirects back to http instead of https.

It seems the solution is to add the `--module=http-forwarded` as an argument to the PlantUML container.
Is it possible to add support for this in the chart? or simply add support for any custom extra arguments?

An example for this can be found in this no-longer-maintained chart:
https://gitlab.com/gitlab-org/charts/plantuml/-/blob/master/templates/deployment.yaml

**Comment by stevehipwell** [comment]
@eranhirs of course we can support it, let me look at the chart and make sure the extra args are available. Would that work for you?

**Comment by stevehipwell** [comment]
@eranhirs do you happen to know if the `--module=http-forwarded` arg works for Tomcat or just Jetty? I'm looking at a potential more advanced solution.

**Comment by stevehipwell** [comment]
@eranhirs I'm still interested if the flag can be automatically set but #431 will close this issue as you will be able to set it manually.

**Comment by eranhirs** [comment]
Perfect, #431 is sufficient for my use case, thanks!
