### ISSUE TITLE
Jira does not regenerate / update dbconfig.xml on DB credential changes

### ISSUE THREAD

**Issue by EugenMayer** [stevehipwell/helm-charts#426]
When changin the credentials of the database, and thus `ATL_JDBC_PASSWORD`, the `dbconfig.xml` will not be updated, the old one is used and the connection does not work.

This can be very surprising and lead to unexpected issues - any reasons you do not regenerate it?

Comparing to confluence in jira this file usually can be regenerated each start without any issues, so it's much simpler to fix.

**Comment by EugenMayer** [comment]
Just have seen that you are using the official images and this is an actual upstream bug (which Atlassian will not fix).

I would suggest we could go with an init container, that deletes the dbconfig.xml on every start.

**Comment by stevehipwell** [comment]
@EugenMayer having unsuccessfully spoken to Atlassian numerous times about this issue I don't really want to spend any engineering time on what is an edge case for an [almost deprecated tool](https://www.atlassian.com/migration/assess/journey-to-cloud). I have provided the `extraInitContainers` input so that people can manage these edge cases themselves. I'm happy to discuss further if you think there is something I've missed or a compelling case for something else otherwise I think this can be closed?

**Comment by EugenMayer** [comment]
I understand, including your POV due to the near EOL of server.

Would you still be interested in a PR if we fix this with a initContainer and would share it?

**Comment by stevehipwell** [comment]
@EugenMayer yes a PR either to automate the init container or just to add to the README how to do it would be appreciated. If the self hosted versions weren't EOL I'd be considering a Helm hook job to manage this task only when the values changed. I guess a marker file with the credentials hashed in it could be used to only run the command on a change.

**Comment by EugenMayer** [comment]
I would keep it simple, 

- configuration value to enable or disable this behavior
- if enabled, the init container removes the dbconfig.xml and it will be recreated.

I would neither go using having and comparing or any further things - if anybody wants to keep the dbconfig.xml out of any reasons, the behaviour should be disabled.

I would opt in to make this the default behavior, but that is on you to decide

**Comment by stevehipwell** [comment]
I'm fine with the KISS approach but wouldn't want to turn it on by default in the chart as that specifically goes against the KISS approach.

If I was using it I'd turn it on as needed but keep it off by default; the pod gets re-started relatively regularly but I can't remember the last time I changed a Jira or Confluence password.
