### ISSUE TITLE
Confluence does not update db credentials if those change

### ISSUE THREAD

**Issue by EugenMayer** [stevehipwell/helm-charts#427]
Changing `ATL_JDBC_PASSWORD` or any other DB related setting does not regenerate `confluence.cfg.xml` - i understand this is a little more tricky with Confluence then with jira #426 - since actual runtime data is saved in that file like the license.

In both cases we could use xmlstartlet to inject just the values we need via https://github.com/EugenMayer/docker-image-atlassian-confluence/blob/master/bin/docker-entrypoint.sh#L81

Any reasons to not do that?

**Comment by stevehipwell** [comment]
@EugenMayer I've responded in #426.
