### ISSUE TITLE
Wildcard Ingress path not working automatically on Sonarqube Helm chart

### ISSUE THREAD

**Issue by rrmnj** [stevehipwell/helm-charts#430]
When using this chart we ran into an issue when using an AWS ALB with Sonarqube. By default, the ingress path '/' does not support the wildcard * in AWS (the case may be different in other cloud providers). This means that after the Ingress ALB has been created, we need to manually go into the AWS console and add the wildcard (*) after the path '/'. This allows Sonarqube to function normally. Without doing this, none of the Sonarqube pages will load.

**YAML for Ingress resource:** 
Source: sonarqube/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  labels:
    helm.sh/chart: sonarqube-4.3.1
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/version: "9.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/group.name: sonarqube
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: [REDACTED]
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: alb
spec:
  rules:
    - host: "[REDACTED]"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarqube
                port:
                  number: 9000

**Kubernetes version**: v1.20.11-eks-f17b81

**Helm Version**: v3.8.0

**Installed chart using the following commands:** helm upgrade --install --namespace sonarqube -f values.yaml sonarqube stevehipwell/sonarqube

**Comment by stevehipwell** [comment]
@rrmnj are you using the out of tree [AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/)? And if so which version? I've seen this behaviour before but only when not setting `pathType: Prefix`; with the latest controller and `pathType: Prefix` set the ALB target groups are created as `/*`.

**Comment by stevehipwell** [comment]
@rrmnj that version is over a year old and I think it even predates the K8s v1.20 release. based on my memory of configuring our ALBs and a quick grep of the releases it looks like you need at least [v2.2.0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.0) to support `pathType`.

**Comment by rrmnj** [comment]
Thanks a lot @stevehipwell. We bumped the alb-controller up to the latest version (v2.4) and that has fixed the issue, therefore closing this ticket.
