### ISSUE TITLE
plantuml: No option for NetworkPolicy 

### ISSUE THREAD

**Issue by phillid** [stevehipwell/helm-charts#435]
I've been using your plantuml chart (nice and clean!). Interestingly, GitLab's docs for deploying plantuml suggest optionally securing the server using [network controls to isolate it][1] in order to remove basic attacks such as fetching cluster-internal URLs via a plantuml instance.

I'm looking towards adding an optional egress-disabling NetworkPolicy to sit alongside the release, which isn't currently supported in the chart, but could be a useful optional feature for others. I could suggest using something as inflexible as the following. More options for tuning the policy might be a bit more palatable for wider use:

```diff
diff --git a/charts/plantuml/templates/networkpolicy.yaml b/charts/plantuml/templates/networkpolicy.yaml
new file mode 100644
index 0000000..8574865
--- /dev/null
+++ b/charts/plantuml/templates/networkpolicy.yaml
@@ -0,0 +1,12 @@
+{{- if .Values.networkPolicy.enabled }}
+apiVersion: networking.k8s.io/v1
+kind: NetworkPolicy
+metadata:
+  name: plantuml-no-egress
+spec:
+  podSelector:
+    matchLabels:
+      {{- include "plantuml.selectorLabels" . | nindent 6 }}
+  policyTypes:
+  - Egress
+{{- end }}
diff --git a/charts/plantuml/values.yaml b/charts/plantuml/values.yaml
index 4c795a7..f444576 100644
--- a/charts/plantuml/values.yaml
+++ b/charts/plantuml/values.yaml
@@ -31,6 +31,9 @@ podSecurityContext: {}

 priorityClassName: ""

+networkPolicy:
+  enabled: false
+
 livenessProbe:
   httpGet:
     path: /png
```

Let me know what you think about this ☺

[1]: https://docs.gitlab.com/ee/administration/integration/plantuml.html#configure-plantuml-security

**Comment by stevehipwell** [comment]
@phillid I'd strongly advise the use of network policies for anything in a K8s cluster but I don't see it as a Helm chart concern. IMHO Helm charts are intended deliver a working "app" into a Kubernetes cluster, anything not required for that doesn't belong in the chart.

**Comment by phillid** [comment]
Thanks for the quick response - that's a fair enough approach. I'll wrap this chart with a custom one in order to achieve this behaviour instead.
