### ISSUE TITLE
nexus3 configure users

### ISSUE THREAD

**Issue by mkuzniarski** [stevehipwell/helm-charts#436]
Hi,

the following error appears while configuring users:
```Updating user 'svc_npm'...
sed: can't read /tmp/anon-user.json: No such file or directory
```
with example config:

```
  users:
    - userId: svc_npm
      firstName: npm
      lastName: npm
      emailAddress: xxx@xx.xx
      source: default
      status: active
      roles:
        - nx-admin
        - nx-npm-admin
        - nx-npm-write
      externalRoles: []

**Comment by stevehipwell** [comment]
@mkuzniarski there is a typo in the script, could you modify the `nexus3-conf` configmap and swap the reference to `/tmp/anon-user.json` with `"${json_file}"` and restart the pod? I'm not going to be able to test this myself for a couple of days.

**Comment by mkuzniarski** [comment]
got it.
there's also a problem with iteration through users:
```  {{- range .Values.config.users }}
  {{ .id }}-user.json: |
    {{- . | toJson | nindent 4 }}
  {{- end }}
```

which ends up with single ```'-user.json'```  file


I guess it should be:

```  {{- range .Values.config.users }}
  {{ .userId }}-user.json: |
    {{- . | toJson | nindent 4 }}
  {{- end }}
```

**Comment by stevehipwell** [comment]
@mkuzniarski I've opened #437 to fix both of these issues. If you can test by manually modifying the config map that would help, otherwise I'll give it a test later in the week.
