### ISSUE TITLE
[confluence-server] ATL_JDBC_URL port formats incorrectly

### ISSUE THREAD

**Issue by mcwarman** [stevehipwell/helm-charts#457]
Using `v4.8.2` our helm terraform diff shows odd formatting around the port:

```text
~ value = "jdbc:postgresql://<host>:5432/confluence" -> "jdbc:postgresql://<host>:%!s(float64=5432)/confluence"
```

**Comment by stevehipwell** [comment]
This was an issue which should have been patched, but I'm AFK so can't figure out exactly why it's still an issue for a day or two.

In the meantime quoting the port value should fix your issue.

```yaml
psql:
  port: "5432"
```
