### ISSUE TITLE
Add support multiple docker repos without publish additional ports

### ISSUE THREAD

**Issue by AlexGluck** [stevehipwell/helm-charts#469]
Hello, i writed full nginx configuration for support multiple repos without publish additional ports [here](https://gist.github.com/abdennour/74c5de79e57a47f3351217d674238da8?permalink_comment_id=4188452#gistcomment-4188452).

In [your ingress](https://github.com/stevehipwell/helm-charts/blob/c2cbf919329703b7540e3837937c7be2f6098cd4/charts/nexus3/templates/ingress.yaml#L25
) not work properly docker repos.

Can you please look my work?

**Comment by stevehipwell** [comment]
@AlexGluck I'm working on some assumptions here as your issue doesn't give me the context of which chart you're using and what you're actually trying to use.

If you're trying to use Nexus3 with multiple Docker connectors this is supported via `service.additionalPorts`, there is no need to write any additional config as the chart handles setting up the connectivity for additional ports with mapped host names.

**Comment by AlexGluck** [comment]
I propose replace additional ports by my variant without any additional ports. After i manage nexus configuration by terraform, i need replace service and update statefullset with stop_the_world for customers.

For improve service quality i request replace your logic by my.

**Comment by stevehipwell** [comment]
Sorry @AlexGluck I don't see the benefit of your approach over the Kubernetes & Nexus native approach used in this chart. This chart doesn't expect Docker repositories (or anything else for that matter) to be configured outside of a maintenance window and I don't think the extra complexity required to support it is worth it. All automated config changes via the chart will result in the deployment being updated so if you're using the chart to configure your repositories it'd restart even with your proposed changes.

If you don't want this capability have you looked at the official chart, I don't think they use this logic. Or you could use this chart but provide your own ingress object and disable the chart ingress, but you'd need to handle configuring Nexus via IaC outside of the chart.
