### ISSUE TITLE
traefik proxy confluence 500 error

### ISSUE THREAD

**Issue by qiang93** [stevehipwell/helm-charts#49]
Hi, 
   Applying your default confluence helm configure will cause 500 errors after entering database connection information

traefik logs:
`{"BackendName":"www.tt.ai/","ClientHost":"10.233.70.0","DownstreamStatus":500,"Duration":1106302817,"OriginDuration":1105784036,"OriginStatus":500,"Overhead":518781,"RequestContentSize":0,"RequestHost":"www.tt.ai","RequestMethod":"GET","RequestPath":"/setup/setupdbtype.action?dbConfigInfo.simple=false\u0026database=postgresql\u0026dbConfigInfo.databaseType=postgresql\u0026forceOverwriteExistingData=true\u0026dbConfigInfo.driverClassName=org.postgresql.Driver\u0026dbConfigInfo.databaseUrl=jdbc%3Apostgresql%3A%2F%2Fpostgresql-debug.postgresql-debug.svc%3A5432%2Fconfluence\u0026dbConfigInfo.userName=root\u0026dbConfigInfo.password=asdf1234\u0026dbConfigInfo.dialect=com.atlassian.confluence.impl.hibernate.dialect.PostgreSQLDialect\u0026atl_token=bc4d17af71abf865ea8b40056be8e9cadea19580","level":"info","msg":"","request_Referer":"http://www.tt.ai/setup/setupdbtype.action","request_User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36","time":"2020-07-22T08:46:51Z"}`

**Comment by stevehipwell** [comment]
Hi @qiang93 I'd need a bit more information about what custom values you pass into the chart as the default config is currently passing CI tests. Could you also rename this issue to reflect the actual issue you're having which seems to be database related and not related to Traefik.

**Comment by qiang93** [comment]
Thanks for your quick response. The installation process of accessing Confluence through NodePort went smoothly, so there is reason to suspect that the application of Traefik caused a proxy error

Env:
`      
        JVM_MINIMUM_MEMORY: "2G"
        JVM_MAXIMUM_MEMORY: "4G"
        JVM_SUPPORT_RECOMMENDED_ARGS: "-Dsynchrony.memory.max=2g"
        ATL_PROXY_NAME: "www.tt.ai"
        ATL_PROXY_PORT: "80"
        ATL_TOMCAT_SCHEME: "http"
`

**Comment by qiang93** [comment]
Repeat steps：change default valules.yaml

ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - www.tt.ai
  tls: []
    # - secretName: confluence-local-tls
    #   hosts:
    #     - confluence.local

**Comment by qiang93** [comment]
Problem solved。

Just letting confluence recreate entire tables again after removing existing confluence-cfg.xml should work next time

**Comment by stevehipwell** [comment]
@qiang93 it looks like this is no longer an issue so I'm going to close this.
