### ISSUE TITLE
SonarQube:  no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by hannes-angst** [stevehipwell/helm-charts#490]
Detecting if the kubernetes cluster uses the stable API for ingress fails on AWS:
```
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
with

```
│ Error: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

Most probably because the version returned is `v1.22.9-eks-810597c`.

**Comment by stevehipwell** [comment]
@hannes-angst how are you applying the chart and what tool versions do you have? The chart is coded to detect the correct ingress API (even with the incorrect SemVer used by the managed K8s offerings) and I've tested it on various Kubernetes versions (specifically EKS).

https://github.com/stevehipwell/helm-charts/blob/95968619f22dd1d5206dac4a16fa2c8d89358c6f/charts/sonarqube/templates/_helpers.tpl#L97

**Comment by hannes-angst** [comment]
I will call this an issue with migrating the cluster.

Uninstalling the chart returns the following issue:
```
$ helm uninstall sonarqube
Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: resource mapping not found for name: "sonarqube" namespace: "" from "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
ensure CRDs are installed first
```

After this, an installation works like a charm :)
