### ISSUE TITLE
[Jira Software] Existing claims do no longer work with statefulset

### ISSUE THREAD

**Issue by EugenMayer** [stevehipwell/helm-charts#493]
While existingClaims are supported with the old deployment variant, they are currently no longer supported with the statefulset kind of deployment.

We should either fix this or maybe add it to the docs.

### To fix it (IMHO)

For
-  https://github.com/stevehipwell/helm-charts/blob/master/charts/jira-software/templates/statefulset.yaml#L175  
- https://github.com/stevehipwell/helm-charts/blob/master/charts/jira-software/templates/statefulset.yaml#L139

we sould use {{ .Values.persistence.existingClaim | default (include "jira-software.pvcname" .) }}

**Comment by stevehipwell** [comment]
@EugenMayer it looks like the docs are missing for the `deployment` value so I'll do a patch release with the following description and update the release notes.

> If `true`, a `Deployment` will be created instead of a `StatefulSet`. Set this to `true` if you're migrating from a version `< v5.0.0` and leave it set to `false` if you're starting with a version `>= v5.0.0`. **IMPORTANT** - Do not change this value after setting it, you could loose your data.

I don't think that the additional complexity of the code and the documentation is worth it to enable supporting existing volumes in the `StatefulSet`, especially as it couldn't be seamless with what's in the chart for the `Deployment`. I'm intentionally not supporting migration, although if you know what you're doing it's fairly simple.

**Comment by stevehipwell** [comment]
See https://github.com/stevehipwell/helm-charts/pull/494.

**Comment by EugenMayer** [comment]
I cannot see how that is overcomplicating things, but Iam not here to argue

**Comment by stevehipwell** [comment]
> I cannot see how that is overcomplicating things, but Iam not here to argue. Find with any direction

You need conditional logic in the templates, and then documentation to explain that you can use an existing `PersistentVolume` as long as it's named correctly (which is not the same as the template name and has ordinals in it), and then more documentation to say that the `PersistentVolumeClaim` created for the `Deployment` wont work with this.

AFAIK Jira Software is effectively dead with people seeing out the last of their licence periods with no option to extend them?

**Comment by EugenMayer** [comment]
With statefulset my opinion is, there are no conditions needed, but hands down, my experience here is limitted.

The dead part is surely right, i guess e.g. for us, we will run it until Feb. 2024 most probably, so quite some time still - but we are users and also vendors. 

Again, do what suits you best, we had our fair share of fun today dealing with the PVC de-attached and restoring the old one

**Comment by stevehipwell** [comment]
> Again, do what suits you best, we had our fair share of fun today dealing with the PVC de-attached and restoring the old one

Sorry about that, it looks like a commit got lost during a rebase which had the README line for the new variable as well as the CHANGELOG warning. I assumed the chart would be dry run for a major version so I didn't make as big a deal out of the change as I could have (not that it even got released anyway).
