### ISSUE TITLE
Nexus3: Unable to import custom CAs

### ISSUE THREAD

**Issue by Jasper-Ben** [stevehipwell/helm-charts#50]
I am trying to import custom CAs into the Nexus3 Trust Store.
For this I set caCerts.secret according to a Kubernetes secret, containing multiple CA.crts.
Applying the settings causes an [error](https://github.com/stevehipwell/helm-charts/files/4960583/error.log). From looking at the deployment.yaml, my first guess would be, that the parent `node` folder does not exist.

**Comment by stevehipwell** [comment]
@Jasper-Ben could you show what values you're using and the structure of the secret?

**Comment by Jasper-Ben** [comment]
Hi @stevehipwell,
the secret looks like this:
```
Name:         ca-certs
Namespace:    nexus3
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
legacy-rsa-ca:  1773 bytes
secure-es-ca:   1314 bytes
secure-rsa-ca:  2464 bytes
```

**Comment by stevehipwell** [comment]
@Jasper-Ben could you add the full logs from the _ca-certs_ init container? I suspect it's something to do with the file system bug that I fixed and can probably be fixed by swapping the init container order.

**Comment by Jasper-Ben** [comment]
@stevehipwell the ca-certs container's log only contains
```
Certificate was added to keystore 
Certificate was added to keystore 
Certificate was added to keystore 
```

**Comment by stevehipwell** [comment]
@Jasper-Ben do you want to try the latest release?

**Comment by Jasper-Ben** [comment]
@stevehipwell Unfortunately still [errors](https://github.com/stevehipwell/helm-charts/files/4966684/error.log) :disappointed:

**Comment by Jasper-Ben** [comment]
just in case: here is my current [values.yml](https://github.com/stevehipwell/helm-charts/files/4966732/helm_values.txt). Hope it helps

**Comment by stevehipwell** [comment]
Could you try again?

**Comment by Jasper-Ben** [comment]
@stevehipwell Nice! That seems to have done the trick on the CA front. However, now I'm back to [LDAP issues](https://github.com/stevehipwell/helm-charts/files/4967372/error.log)... I assume `groupIdAttribute` should not fail, as I have `mapGroupAsRolesType` set to "dynamic"?
