### ISSUE TITLE
tigera-operator: missing kubeletVolumePluginPath field from calico v3.24.0 Installation CRD

### ISSUE THREAD

**Issue by gclawes** [stevehipwell/helm-charts#505]
tigera-operator v1.28.0 added CSI Driver support: https://github.com/tigera/operator/releases/tag/v1.28.0

The merge for this includes the new `.spec.kubeletVolumePluginPath` field in the `Installation` CRD: [pkg/crds/operator/operator.tigera.io_installations.yaml](https://github.com/tigera/operator/pull/2082/files#). Setting this field to `None` allows the CSI driver integration to be disabled, which is desirable on clusters that do not use the Istio/Dikastes integration.

This field appears to be missing in the chart CRDs.

**Comment by gclawes** [comment]
Ahh, it looks like the `kubeletVolumePluginPath` may not have made it into their CRDs for v3.24.0.

I see it in `master` (permalinks to the current master commit):
https://github.com/projectcalico/calico/blob/0e8541c9b6397f74c2f4a4471e6cff4892dc44af/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml#L4245
https://github.com/projectcalico/calico/blob/0e8541c9b6397f74c2f4a4471e6cff4892dc44af/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml#L10397

But it's not in v3.24.0: https://github.com/projectcalico/calico/blob/v3.24.0/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml

Here's the commit that added it 3 days ago (v3.24.0 was 7 days ago): https://github.com/projectcalico/calico/commit/a6c67dfea6ec63a02204c54a28db290c2efa6a7a

Hopefully they'll fix it in a subsequent release.

**Comment by stevehipwell** [comment]
@gclawes it might be worth opening an issue if you think it's been missed?

**Comment by gclawes** [comment]
Opened: https://github.com/projectcalico/calico/issues/6620

**Comment by stevehipwell** [comment]
This was fixed in the last release.
