### ISSUE TITLE
[nexus3] Some volumes missing in statefulset

### ISSUE THREAD

**Issue by timdeluxe** [stevehipwell/helm-charts#516]
volumeMounts are there, but volumes are missing in the statefulset.yaml for everything coming from configmaps or secrets. In deployment.yaml they are there.

**Comment by stevehipwell** [comment]
@timdeluxe I'll take a look when I'm back in the office next week.

**Comment by stevehipwell** [comment]
@timdeluxe this should be fixed in the release that's just been created.
