### ISSUE TITLE
Nexus3: Adapt groovy scripts for newer Nexus3 Releases

### ISSUE THREAD

**Issue by Jasper-Ben** [stevehipwell/helm-charts#53]
There have been some changes within the Nexus3 codebase, causing some of the groovy scripts not to work.
So far, I was able to confirm that repo.groovy and cleanup.groovy do not work.

![repo.groovy](https://user-images.githubusercontent.com/12223583/88367193-6e209a00-cd8b-11ea-8d5e-5908df7a9252.png)

![cleanup.groovy](https://user-images.githubusercontent.com/12223583/88367148-577a4300-cd8b-11ea-835a-4efefeb99a36.png)

In the case of the repo.groovy script, this seems to be due to https://issues.sonatype.org/browse/NEXUS-22819.

I am currently working on fixing these issues. Unless @stevehipwell can think of a reason not to, I will try to use the REST API instead (whenever possible), as I assume it will change less frequently.

**Comment by stevehipwell** [comment]
@Jasper-Ben I wasn't aware that the scripts were no longer working but I've been gradually upgrading to the REST API where possible. I've got a branch locally that replaces everything but cleanup, which isn't supported on the API, that I could possibly get released next week (I was holding off for v3.25 to see if cleanup was added). I should probably add a ticket to Nexus3 for a cleanup API.

**Comment by Jasper-Ben** [comment]
@stevehipwell delivers again! :wink: Sounds great! Please feel free to point me towards any work that is still left to be done. I already feel guilty for showering you with all the issues popping up :laughing:

**Comment by stevehipwell** [comment]
No worries @Jasper-Ben, thank you for your help testing the changes! I did offer to donate my chart to Sonatype but they never got back to me and after the work I've done to make it work for others I think I'll keep maintaining it myself (they can always fork it).

**Comment by stevehipwell** [comment]
FYI @Jasper-Ben [REST for cleanup policies](https://issues.sonatype.org/browse/NEXUS-17671).

**Comment by stevehipwell** [comment]
@Jasper-Ben if you want to take a look at PR https://github.com/stevehipwell/helm-charts/pull/56 which is a full refactor of the _Nexus 3_ chart. The values have changed to hopefully make the chart easier to use and I've documented more of the configuration. If you want to try it out and let me know how you get on I'll attempt to fix obvious bugs, otherwise I'll be waiting until I have more time to test it out myself.

**Comment by Jasper-Ben** [comment]
@stevehipwell great! I will give it a try

**Comment by stevehipwell** [comment]
@Jasper-Ben should this be closed now?
