### ISSUE TITLE
[jira-software] k8s API error

### ISSUE THREAD

**Issue by lwsanty** [stevehipwell/helm-charts#55]
helm 3
gke 1.16.9-gke.6

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

**Comment by stevehipwell** [comment]
@lwsanty please could you provide more information?

**Comment by lwsanty** [comment]
@stevehipwell sure, according to deprecation of k8s api 1.16 https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
```
StatefulSet in the apps/v1beta1 and apps/v1beta2 API versions is no longer served
```
so the chart installation will be failing for k8s api 1.16 unless correct api versions will be handled on the chart level.

**Comment by lwsanty** [comment]
forgot to mention the chart name, `jira-software`

and now I see that it is related to postgres subchart

then not a bug, sorry
