### ISSUE TITLE
Istio-Operator Helm Chart v2.8.0 - appVersion is wrong

### ISSUE THREAD

**Issue by Starslider** [stevehipwell/helm-charts#554]
Hi Steve

looks like you have an old appVersion in your Chart.yaml - could that be? 

```
apiVersion: v2
name: istio-operator
description: Helm chart for the Istio Operator.
type: application
version: 2.8.0
appVersion: 1.8.0
```

it should be 
appVersion: 1.16.0

Best Dominik

**Comment by stevehipwell** [comment]
@Starslider it should be fixed now although I haven't been able to get the correct version showing in Artifact Hub.

**Comment by Starslider** [comment]
did you push it to github? @stevehipwell

**Comment by stevehipwell** [comment]
It's the same version, I manually patched it.

**Comment by stevehipwell** [comment]
@Starslider could you let me know if it's working for you so I can either close this issue or look at an alternate fix?

**Comment by Starslider** [comment]
@stevehipwell where did you fix it? [Chart.yaml](https://github.com/stevehipwell/helm-charts/commits/istio-operator-2.8.0/charts/istio-operator/Chart.yaml) was not updated?

**Comment by stevehipwell** [comment]
@Starslider _Chart.yaml_ is how the release is generated but meaningless in the context of a released chart at the repo. I updated the release artifact and the chart repo index; I also confirmed that these changes showed up correctly on the Helm CLI.
