### ISSUE TITLE
Downtime each nexus configuration change

### ISSUE THREAD

**Issue by holmesb** [stevehipwell/helm-charts#579]
Hi,

Great that nexus chart offers declarative configuration, but currently the configure.sh script only runs at startup, which means the pod gets restarted each change. Would be better to use a sidecar container. This will watch for changes to the configmap and run the script on-the-fly without downtime. I can create PR if\when I get the chance.

Cheers.

**Comment by stevehipwell** [comment]
@holmesb thanks for thinking about this. A sidecar is one option I've considered but I think my preferred option is to move the config out into a job. It should be possible to remove the shared filesystem requirement by starting with a known default password and working from there. I'd be happy to accept a PR, I was waiting for cleanups to be supported in the API which doesn't seem to have progressed at all.
