### ISSUE TITLE
Nexus3: Extend chart features

### ISSUE THREAD

**Issue by Jasper-Ben** [stevehipwell/helm-charts#58]
Just a heads up on the configuration features I plan on implementing. @stevehipwell please stop me if any of them are already implemented or in the pipeline :wink: 

- adding blobstores
- security roles
- remove preconfigured repositories

Additionally: Health-check for Kubernetes

**Comment by Jasper-Ben** [comment]
- create proxy repositories

**Comment by stevehipwell** [comment]
Roles and all types of repository are supported including proxy ones. You can deactivate default repos by setting online to false. Blobstores should be easy to configure via the API. The health check is related to metrics which are enabled as is the status.

**Comment by Jasper-Ben** [comment]
I just found a reference to `.Values.config.roles` in `templates/config.yaml`, however it seems to be missing in the documentation?

**Comment by stevehipwell** [comment]
@Jasper-Ben docs updated.

**Comment by Jasper-Ben** [comment]
Working blobstore configuration in PR https://github.com/stevehipwell/helm-charts/pull/63. Closing.
