### ISSUE TITLE
[nexus3] 3.47.0 image not available on dockerhub

### ISSUE THREAD

**Issue by CC007** [stevehipwell/helm-charts#615]
# Problem
The sonatype/nexus3:3.47.0 docker image seems to be missing on dockerhub. 

# Solution
3.47.1 is available, so it the appVersion in Chart.yaml can be updated to that version.

**Comment by stevehipwell** [comment]
@CC007 thanks for making me aware of this, they must have removed the image as the repo automation won't release a chart unless it deploys successfully. Until I release the next version you can just specify a manual value for `image.tag`.

**Comment by CC007** [comment]
Also, I tried upgrading to it, but my full cluster froze up when I did. No such issues with 3.46.x.

**Comment by stevehipwell** [comment]
@CC007 I'd suggest you report the issue on the Nexus bug tracker if that's what you're seeing. It does look like they retrospectively marked the GH releases as a pre-relesse, which combined with the missing image doesn't sound great. Unfortunately there isn't much structure around the release process to let me monitor any of this.

The only thing to change in the last chart release was the image version. My automation checks that the chart runs but offers nothing more.

**Comment by CC007** [comment]
Thanks for the update. I was worried when there wasn't any first party helm chart, but yours seems to work flawlessly (apart from sonatype's own screwup) and you are very quick without your updates.

**Comment by stevehipwell** [comment]
@CC007 there was an official chart (now deprecated) but it wasn't created until well after I created mine (I offered to donate mine to Sonartype), it also didn't support a lot of the functionality I had implemented and needed (such as additional ports for Docker).

I would strongly recommend running my chart as a StatefulSet (`deployment` set to `false`).
