### ISSUE TITLE
[nexus3] OLowDiskSpaceException

### ISSUE THREAD

**Issue by CC007** [stevehipwell/helm-charts#632]
When using your nexus chart v4.22.0, I get the following error:
```
com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'OSystem' due to limited free space on the disk (2621 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 4096 MB. Required space is now set to 4096MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) . 
```
This is with the default 8GB persistent volume setting, but also when setting it to 16GB. 

Downgrading to v4.20.0 fixes the issue (I didn't test with v4.21.x due to my bad experiences with that version last time).

**Comment by stevehipwell** [comment]
@CC007 the only changes between these versions are in the image used so I'd suggest looking into this on the Nexus side.
