### ISSUE TITLE
[nexus3] Multiple ingress objects

### ISSUE THREAD

**Issue by artificial-aidan** [stevehipwell/helm-charts#655]
We need to deploy multiple ingress objects with our nexus deployment. I have some time to implement this but was wondering if you had input on the design.

I was thinking of leaving the existing ingress how it was, and adding an `additionalIngresses` field in `values.yaml` that would be multiples of the current ingress layout. This would maintain backwards compatibility while allowing expansion.

**Comment by artificial-aidan** [comment]
To create a docker repo I'm using an ingress object that does a prefix rewrite.

So `docker.mydomain.com` does a prefix rewrite where it takes anything at `/(.*)` and redirects to `/repository/docker/$1`. The docker registry api does not support existing at a subpath.

The other use case is extra protection. I only want to expose certain paths outside our VPN (public repositories) but for extra security I want the base nexus path, and other private repos to not be exposed outside of the VPN. To do this I'm doing a prefix match on public repositories, and using a normal ingress object to open them. Then I have a secondary ingress matching on `/` that uses allow-lists to only let VPN access to the other paths.

**Comment by stevehipwell** [comment]
@artificial-aidan the chart already supports handling Docker repositories via the `service.additionalPorts` values which allows mapping ports to additional hosts in the ingress resource. Is there a reason this doesn't work for you?

I don't like to add additional complexity to these charts unless the advantage is worth the effort, I can't see a compelling case as to why there is any advantage to adding multiple ingress resources in the chart.

**Comment by artificial-aidan** [comment]
That sounds like it will work for the docker repositories, I'll try that out. I'm not sure how the prefix rewrite will work, I'm worried that the rewrite will happen even on the host I don't want it to. I'll need to give it a shot. Have you been able to do it a different way?

I understand the concern about complexity. I'll look things over again and see if there's a way I can handle it differently. I think by being able to set the service name I can probably handle my VPN use case outside the helm chart.
