### ISSUE TITLE
[nexus3] Allow user credentials specified by kubernetes secret

### ISSUE THREAD

**Issue by springroll12** [stevehipwell/helm-charts#699]
### Description

From what I can see, except for the admin user, users generated by this helm chart are given a randomly generated password. In most cases it makes sense to pre-generate these passwords and feed them into the chart via a kubernetes secret.

Would it be a simple task to allow this?

**Comment by springroll12** [comment]
Yes I was referring to `config.users`.

I would love to use an external auth system for Nexus but the OSS version does not support it natively. There is a lot of extra effort in figuring out how to handle authorization for different types of repositories that seems non-trivial to implement. If you know of a simple way to do this other than proxy authentication then I would love to hear it.

I don't think it would be difficult to add an optional field for the name of the secret or env variable to use for specific users?

**Comment by stevehipwell** [comment]
@springroll12 you can use LDAP and configure it through my Helm chart.

**Comment by springroll12** [comment]
@stevehipwell Unfortunately LDAP is not available to us. I think this is not uncommon, especially for small deployments of nexus. Would it be possible to update the chart to pull username/passwords or even full `x-user.json` files from a secret?

It might be possible to achieve this by mounting x-user.json files to the `${base_dir}/conf/` directory per https://github.com/stevehipwell/helm-charts/blob/main/charts/nexus3/files/configure.sh#L61 ?

**Comment by EugenMayer** [comment]
@springroll12 if you terraform you can use https://registry.terraform.io/providers/datadrivers/nexus/latest/docs to configure your entire nexus. 

I was very surprised to see which customization level @stevehipwell included in this charts .. with all the config parts. Impressive but also a huge maintenance effort for a helm chart. Kudos!

**Comment by springroll12** [comment]
@stevehipwell No problem. As @EugenMayer mentioned we greatly appreciate you maintaining the chart as it stands. 

We are looking at creating an "extraInitContainer" to solve this for ourselves, and if it makes sense we will make a PR or comment here for posterity.

**Comment by stevehipwell** [comment]
@springroll12 if you're engineering something and would like to contribute a PR I'd consider something for this similar to how you can pass repo credentials via a secret.

**Comment by springroll12** [comment]
For what its worth, we did not end up using an initContainer or modifying the helm chart to suit our needs. In the end we wrote a modified configure.sh which mapped the users we needed to static secrets loaded in via environment variables. Then we used helm post-render hooks to replace the postInit command of the nexus deployment with a command to run our custom configure.sh.

Not really an elegant or scalable solution, so we don't think it's worthy of contributing. However it may help future folks looking to do something similar.

**Comment by stevehipwell** [comment]
@springroll12 do you still require this functionality? I've refactored the chart and this should be possible in the same way the repo secrets are handled.

**Comment by mreiche** [comment]
> @springroll12 do you still require this functionality? I've refactored the chart and this should be possible in the same way the repo secrets are handled.

I need it for fully automated rollout without LDAP. How is your approach implemented?

**Comment by stevehipwell** [comment]
@mreiche it's on the README under `config.ldap` using the standard secret/key pattern.

```yaml
config:
  ldap:
    authPassword:
      secret: my-secret
      key: password
```

**Comment by stevehipwell** [comment]
@mreiche sorry I missed the **WITHOUT** part of your comment. This hasn't been implemented yet, but I'm happy to add it.

**Comment by springroll12** [comment]
@stevehipwell This is fantastic! I think we'll be doing away with our hacky approach in the near future!
