### ISSUE TITLE
Installing JIRA with postgres fails on kubernetes 1.16

### ISSUE THREAD

**Issue by infinytum** [stevehipwell/helm-charts#7]
I'd like to report a bug regarding your JIRA chart, specifically its integrated postgres chart.

On Kubernetes 1.16, the Kind "Deployment" and many more have been moved from extensions/v1beta1 to apps/v1 . Your chart is updated properly, but the postgres dependecy is not. 

Without the postgres enabled, the chart works fine though!

**Comment by stevehipwell** [comment]
Until recently Jira & Confluence were only supported on versions of PostgreSQL up to v9.6 (although Jira would run on v10) so I targeted my charts against the latest Helm chart for v9.6 which was v1.0.0. This postgresql chart uses an API version not supported on K8s v1.16.

Both Jira and Confluence now support the use of PostgreSQL v10 so I'll bump the postgresql chart to v4.2.2, which is the latest chart for PostgreSQL v10, in my Jira and Confluence charts.

**Comment by stevehipwell** [comment]
PR https://github.com/stevehipwell/helm-charts/pull/8
