### ISSUE TITLE
Sonatype Nexus: Add support for jvmAdditionalOptions

### ISSUE THREAD

**Issue by ikappas** [stevehipwell/helm-charts#71]
Hi Steve,

And thank you for your helm repo!

In order to fix `Available CPU` warning in nexus application one would need to pass `-XX:ActiveProcessorCount=<NUMBER_OF_CORES>` to INSTALL4J_ADD_VM_PARAMS.

It would be nice to introduce `jvmAdditionalOptions` in order to facilitate passing additional parameters via INSTALL4J_ADD_VM_PARAMS.

See also:
https://stackoverflow.com/questions/56946027/nexus-sonatype-nexus33-17-0-on-docker-tells-its-using-only-one-cpu

**Comment by stevehipwell** [comment]
Hi @ikappas, if you want to take a look at PR #72 this should solve your problem. This was an oversight on my behalf as I thought I'd already implemented this pattern for Nexus, but it looks like it was only done for Jira and Confluence.

**Comment by ikappas** [comment]
@stevehipwell Looks good!

**Comment by stevehipwell** [comment]
@ikappas that's been released.

https://github.com/stevehipwell/helm-charts/releases/tag/nexus3-3.1.1
