### ISSUE TITLE
FR: thoughts about adding tar to the nexus container 

### ISSUE THREAD

**Issue by EugenMayer** [stevehipwell/helm-charts#736]
First of, again thank you for the great helm charts. As usual, such a great quality, even plugin support and all those things that the official chart is missing (which is where i'am migrated from).

One issue that follows up though, since it is actually the issue of the docker-image offered by sonatype, is missing `tar`. The problem with tar is, without it, `kubectl cp` becomes hugely cumbersome and especially when one wants to get the backup / restore the backup/push it or do something alone those lines, this things become problematic.

I guess there are a couple of options to go about this:
1. we ask sonatype to add the binary - would be this repo https://github.com/sonatype/docker-nexus3 .. no issue queue, so might be a PR only. Oddly, they use tar due to the build and i cannot see them removing the binary - still it missing. Maybe i miss something or the dockerfiles are not what they actually release. I did not compare the build layers yet with the instructions since i'am on the road
2. everyone using your charts adds `root` init container that adds the binary (maybe something like https://github.com/luciusmagn/tar-static) and overrides the cmd to copy that binary from a share volume to /usr/local/bin and make it `nexus` user executable

I really understand that this is a lot of effort and i'am not sure this is worth it. I just wanted to share the actually issue with you - fine to just close it as "that wont happen".
The problem with kubectl cp is .. it is ok it does not work until you really need it. 

In any case, would like to have your thoughts on this

**Comment by stevehipwell** [comment]
@EugenMayer thanks for the feedback it's appreciated.

On this issue my suggestion would be to get the binay onto the image as I'm not comfortable breaking security constraints as part of the Helm chart. The chart is pretty customisable so you could use an init container to do something clever but I don't think I'll be supporting anything to natively modify the image (I'm planning on making it secure by default including using a R/O file system if possible).

FYI I suspect that the `RUN microdnf remove -y gzip shadow-utils` command removes `tar`.
