### ISSUE TITLE
geting Issue in using helm chart for nexus

### ISSUE THREAD

**Issue by shankar96** [stevehipwell/helm-charts#78]
identified at least one change, exiting with non-zero exit code (detailed-exitcode parameter enabled)

Upgrading stevehipwell/nexus3
Creating tiller namespace (if missing): kube-system
Release "nexustest" does not exist. Installing it now.

in helmfile.d/202.nexus.yaml: failed processing release nexustest: helm exited with status 1:
  Error: release nexustest failed: Ingress.extensions "nexustest-nexus3" is invalid: spec: Invalid value: []networking.IngressRule(nil): either `backend` or `rules` must be specified
  Error: plugin "tiller" exited with error

**Comment by stevehipwell** [comment]
@shankar96 you need to provide any missing ingress parameters if you enable ingress. Do you have your values for ingress to show me?

**Comment by shankar96** [comment]
@stevehipwell it was indentation issue have fixed it thanks.
Now using https://github.com/Oteemo/charts/tree/master/charts/sonatype-nexus (seems to be official one moved here)

**Comment by stevehipwell** [comment]
@shankar96 there is no official chart, that is the chart that was previously in stable. My chart had a number of improvements, such as the ability to map multiple hosts for running Docker registries.
