### ISSUE TITLE
bug(confluence-server): No template "postgresql.primary.fullname"

### ISSUE THREAD

**Issue by Hounddog** [stevehipwell/helm-charts#805]
Trying to use this chart we receive this error "no template "postgresql.primary.fullname" after upgrading from version 5.5.1 to 5.6.0.
It seems that the new chart also references a new postgresql chart.

In this chart the the template has changed to postgresql.v1.primary.fullname

Issue Line: https://github.com/stevehipwell/helm-charts/blob/d09ffa45fb35dbbb79de9c8d50fed1fdc77d840f/charts/confluence-server/templates/_helpers.tpl#L158

https://artifacthub.io/packages/helm/bitnami/postgresql/12.12.10?modal=template&template=_helpers.tpl&compare-to=11.9.13

View the template changes for the helpers here.

**Comment by stevehipwell** [comment]
Thanks for raising this @Hounddog and sorry for the slow reply. I'll get this fixed this week, it looks like it slipped past me as I only use the sub-chart for specific testing scenarios.

FYI I'd strongly recommend against using the PostgreSQL sub-chart for anything other than testing. If I was running PostgreSQL in a K8s cluster I'd be using an operator such as EDB.

**Comment by Hounddog** [comment]
This is exactly what we are doing. We generate previews using the PostgreSQL sub-chart. We are currently implementing crossplane and probably we will also move away deploying previews with PostgreSQL and instead create an AWS RDS resource.
