### ISSUE TITLE
More info regarding blob store configuration for Nexus

### ISSUE THREAD

**Issue by jmccrumm** [stevehipwell/helm-charts#849]
The nexus3 helm chart README.md states the following information about the key `config.blobStores`: "Blob stores to be configured (see `values.yaml` for structure)." Referencing the values file as suggested, the only example given is of type `file`. It would be nice if more examples were given, particularly which keys are required to configure an `s3` blob store.

**Comment by stevehipwell** [comment]
@jmccrumm the README could be updated to show that most of these structures should follow the REST API data structure; but unless something has changed recently this is vary hard to pin down in static linkable documentation.

**Comment by jmccrumm** [comment]
@stevehipwell that's fair. It took me a while but I was able to figure out that it correlated with the REST API. I think there may be a bug with Nexus itself when specifying `softQuota`. The type under that seemed to be overriding the `type: s3`. At one point the logs said `Could not find resource for full path: http://localhost:8081/service/rest/v1/blobstores/spaceRemainingQuota/my.bucket`. Obviously there's nothing you could do about this, but I found that behavior odd.

Anyway, I do think the README at least mentioning that the blobStores configuration structure matches that of the REST API docs would be helpful.

Thanks for your quick response.

**Comment by stevehipwell** [comment]
@jmccrumm I'm happy to take contributions, especially for documentation.

I don't personally use this chart anymore even though I keep it well maintained. I'm still waiting, many years later, for cleanup policy support via the API. At that point I plan on refactoring the configuration to API only via a Job instead of the entrypoint script.

**Comment by jmccrumm** [comment]
I made a pull request [here](https://github.com/stevehipwell/helm-charts/pull/851) with a note in `values.yaml` (since the README already points people to that)
