### ISSUE TITLE
Allow overriding repository for init containers in Nexus helm chart

### ISSUE THREAD

**Issue by jmccrumm** [stevehipwell/helm-charts#850]
We install the nexus3 helm charts using our own custom core registry (we have a registry containing the nexus3 images only, then nexus3 itself serves up the images for all our normal services). That being said, we override the `image.repository` helm value to point to this custom core registry. However, the `initContainers` in the `deployment.yaml` (and `statefulset.yaml`) hardcode the `image` values, forcing us to make edits to those specs manually. It would be convenient if the init containers could override the repository they are obtained from via helm values as well.

**Comment by stevehipwell** [comment]
@jmccrumm I'd be willing to add values to override the init container image but it's not implicitly related to the primary image so the current values aren't relevant. I was already planning on changing the default to a Chainguard image for zero CVEs.

**Comment by jmccrumm** [comment]
@stevehipwell Sounds great, thank you!

**Comment by stevehipwell** [comment]
@jmccrumm this should be fixed in the [v5.0.0](https://github.com/stevehipwell/helm-charts/releases/tag/nexus3-5.0.0) chart release.
