### ISSUE TITLE
[thanos] How to implement authentication

### ISSUE THREAD

**Issue by amrap030** [stevehipwell/helm-charts#877]
Hello,

I would like to implement basic authentication for thanos. When I look at the docs, it seems that it is possible to create a configuration file and add it via the flag `--http.config` (https://thanos.io/tip/operating/https.md/), but I am not sure how to do this in the helm chart. Is this possible?

**Comment by stevehipwell** [comment]
@amrap030 you can't currently do this as the Thanos components don't currently have `extraVolumes` & `extraVolumeMounts` values. I can add these inputs to the chart if you'd like, at which point you'd need to create the `ConfigMap` outside the chart and pass it into the relevant component via the `extraVolumes` & `extraVolumeMounts` values?

**Comment by onedr0p** [comment]
Volume mount would also be good to mounting in config to enable caching with redis or memcache

https://thanos.io/tip/components/store.md/#index-cache

**Comment by stevehipwell** [comment]
@onedr0p that's a good point, let me take a look at adding additional volume support.
