### ISSUE TITLE
Would you add `resources.extra` field so that I can add my gpu value into the resource?

### ISSUE THREAD

**Issue by pjeon2** [stevehipwell/helm-charts#901]
Hi, I would like to add gpu values into `requests`

Here is some example

``` resources:
            requests:
              cpu: 10m
              memory: 16Mi
              nvidia.com/gpu: "1"
```

To demonstrate what I need, I created a PR in my repo after forking helm-charts
https://github.com/stevehipwell/helm-charts/pull/900

Would you kindly consider adding this code into helm chart?

**Comment by stevehipwell** [comment]
@pjeon2 I'm happy to support this use case. I've added a couple of comments to your PR for how we could do this.
