### ISSUE TITLE
[Nexus3] Deployment doesn't scale more than one

### ISSUE THREAD

**Issue by Nithinrao9696** [stevehipwell/helm-charts#910]
When setting the deployment replica to 2 , second pod doesn't come up and stuck in init mode

**Comment by stevehipwell** [comment]
@Nithinrao9696 I assume that you mean that you're setting the StatefulSet replicas to 2 via the `deployment=false`, `highAvailability.enabled=true` & `highAvailability.replicas=2` values? Otherwise the chart only supports a single pod.

**Comment by stevehipwell** [comment]
@Nithinrao9696 OSS Nexus only supports a single replica, and unless you're setting the values above you shouldn't be able to create more than 1.

**Comment by Nithinrao9696** [comment]
> to

@stevehipwell so we can't create multiple replicas or is there some workaround where we can have replica count more than 1

**Comment by stevehipwell** [comment]
@Nithinrao9696 Nexus OSS doesn't support HA (more than 1 replica) and the chart doesn't support configuring more than 1 replica without specifying that you're using the licenced HA feature specifically because of this.

**Comment by Nithinrao9696** [comment]
@stevehipwell Is it the limitation from nexus OSS image or the way that the helm charts are designed? Will it be possible to update the charts to support or have multiple replicas?

**Comment by stevehipwell** [comment]
@Nithinrao9696 it's an intentional limitation for Nexus OSS; Sonatype require you to buy a licence for HA. The chart can do multiple replicas if you've got a license.
