### ISSUE TITLE
[nexus]  Ldap password escaping \ breaks other passwords that have sed special characters (&)

### ISSUE THREAD

**Issue by joshzcold** [stevehipwell/helm-charts#911]
If I have 
`mypass&!` and we are replacing `PASSWORD` the result is `mypassPASSWORD!` because sed treats `&` (and probably some other characters) as a function in the replace statement.

Which means the next step would be to escape `&` so that sed keeps it in place.

`mypass\&!`  

However the current sed pattern `sed 's|"|\\"|g;s|/|\\/|g;s|\\|\\\\|g'` adds an extra escape that invalidates the escape on the `&` resulting in `mypass\PASSWORD!`

Going back to `nexus3-4.40.0` fixes my specific issue, but I wanted to file this in case there was something I or someone else could do to make this fool proof.

Personally I feel as though its up to the deployer to supply a password that the nexus api or json will accept and we shouldn't in configuration modify the contents of `"${base_dir}/secret/ldap.password"` , but I know others have put in fixes specifically to handle their password.

https://github.com/stevehipwell/helm-charts/blob/21b10ded488a4bc2fc1d81b86054542040eec7dc/charts/nexus3/files/configure.sh#L147

**Comment by stevehipwell** [comment]
@joshzcold it looks like this was introduced in #897 and there is a conversation on #905 about how to fix it.

**Comment by stevehipwell** [comment]
@joshzcoldon reflection I agree with you, but as the code has already been made to work I think it should probably stay. That said I'd be keen to get a list of failing characters which I could add to a guard clause if they weren't made to work correctly.

**Comment by joshzcold** [comment]
https://unix.stackexchange.com/questions/32907/what-characters-do-i-need-to-escape-when-using-sed-in-a-sh-script

Looks like just along with `\` we could escape `&` as well. 

Im thinking using `envsubst` could be a solution to work with any password available (I could get a pull going) 

example:
`envsubst "\$PASSWORD" < /etc/request.json > /tmp/secret.json`

But does that also have a possibility of not working with special bash characters? Im not sure.
