### ISSUE TITLE
[nexus3] Setting rootPassword.key has no effect

### ISSUE THREAD

**Issue by nicoangelo** [stevehipwell/helm-charts#922]
Hi,

When setting a value for `rootPassword.key` the templating logic will always take the default value, no matter what is defined. It only works when using the deprecated value of `config.rootPassword.key`.

The issue is in the usage of the `default` function and the defined default values: https://github.com/stevehipwell/helm-charts/blob/main/charts/nexus3/templates/deployment.yaml#L113

```
{{ default .Values.rootPassword.key .Values.config.rootPassword.key }}
```

According to https://helm.sh/docs/chart_template_guide/function_list/#default, the `default` function will take the second argument, if its not null. Because `config.rootPassword.key` has a default value of `password` assigned, it will never use the first argument.

Not sure how to solve that, but took us a good while to figure this one out :laughing: In the meantime we just resorted to using the deprecated `config.rootPassword.key`

**Comment by stevehipwell** [comment]
Thanks for spotting this @nicoangelo. The template logic is correct; we want to use the original (now deprecated value) if it's been explicitly set. But I haven't cleared the default deprecated value which would require you to either use the legacy value or unset it to make the correct logic work.

**Comment by nicoangelo** [comment]
Makes sense. Thanks for the quick fix!
