### ISSUE TITLE
[nexus3] Question: Requirement for groovy script files in helm chart? 

### ISSUE THREAD

**Issue by timdeluxe** [stevehipwell/helm-charts#964]
Hi Steve,
i hope you are fine with asking a question here via this issue about the Nexus helm chart:

In the files folder you include three groovy scripts, which are "loaded" via a config map and finally loaded as scripts into Nexus via the configure.sh script.
We want to disable scripting in Nexus, since it is a security recommendation by Sonatype, but this fails due to that.

Can you shed some light on those scripts you included there? Are those standard or required for base functionality of Nexus?

**Comment by stevehipwell** [comment]
@timdeluxe scripting is required to configure nexus via the chart. I think the repo and task scripts could be replaced by API calls but cleanup is currently [not supported](https://github.com/sonatype/nexus-public/issues/149). I don't actually still run this chart in production so I'm keeping this maintained but not adding significant effort. If the cleanup API was added then I'd replace all of the groovy scripts as they could be disabled at that point. I'd also likely switch out the configuration implementation to a Helm hook job.

**Comment by timdeluxe** [comment]
Thanks @stevehipwell - that explains it. Looking at the other issue and the linked 5 years old issue, it doesn't look to get implemented soon, so i am going close the issue here. It does not make sense to keep it open, because the question is kind of answered.
